---

- name: set timezone to {{ cs_timezone }}
  timezone:
    name: "{{ cs_timezone }}"
  when: cs_set_timezone is true

- name: install packages for Debian family
  block:
    - name: install default packages for Debian family
      apt:
        update_cache: yes
        name: "{{ cs_debian_packages }}"

    - name: install ext packages for Debian family
      apt:
        name: "{{ cs_debian_ext_packages }}"
      when: cs_debian_ext_packages|length>0
  when: ansible_os_family == "Debian"

- name: install packages for RedHat family
  block:
    - name: install default packages for RedHat family
      yum:
        update_cache: yes
        name: "{{ cs_redhat_packages }}"

    - name: install ext packages for RedHat family
      yum:
        name: "{{ cs_redhat_ext_packages }}"
      when: cs_redhat_ext_packages|length>0
  when: ansible_os_family == "RedHat"

...
