---

- name: set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"
  when: set_timezone is true

- name: install packages for Debian family
  apt:
    update_cache: yes
    name: "{{ debian_packages }}"
  when: ansible_os_family == "Debian"

- name: install packages for RedHat family
  yum:
    update_cache: yes
    name: "{{ redhat_packages }}"
  when: ansible_os_family == "RedHat"

...
